### ISSUE TITLE
Cannot `clear` in shell session

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-os#18]
```
$ clear
clear: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```

```
$ reset
reset: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```

**Comment by ghost** [comment]
This is due to `ncurses` building `clear` and `reset` binaries that we don't need (Busybox has them covered), and then failing to dynamically link (presumably because the CLI utilities somehow built against a system `libncurses` with a slightly different name).

This caused problems in other areas of the build as well and am currently looking at those. IMO, the proper thing to do is to only ship one set of `clear` `reset` utilities with the base system image beneath `/bin`. Sound reasonable?

**Comment by ghost** [comment]
Fixed in https://github.com/medic/medic-os/commit/c399281e82705ece92176cdd24b2275d8dea0608.
